# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(540, 360)
        Dialog.setMinimumSize(QtCore.QSize(540, 360))
        Dialog.setMaximumSize(QtCore.QSize(540, 360))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 80, 211, 51))
        self.label.setStyleSheet("font: 25 12pt \"Microsoft YaHei\";\n"
"font: 25 10pt \"Microsoft YaHei\";\n"
"font: 18pt \"Agency FB\";")
        self.label.setLineWidth(1)
        self.label.setMidLineWidth(0)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(90, 250, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 250, 111, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(0, 0, 601, 401))
        self.listView.setStyleSheet("background-image:url(:/BG.jpg)")
        self.listView.setObjectName("listView")
        self.listView.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.go_text) # type: ignore
        self.pushButton_2.clicked.connect(Dialog.go_num) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "快递信息识别"))
        self.label.setText(_translate("Dialog", "快递信息识别"))
        self.pushButton.setText(_translate("Dialog", "快递文字信息识别"))
        self.pushButton_2.setText(_translate("Dialog", "快递编码识别"))
import data.resources_rc
